### ISSUE TITLE
Update 9/7 ToDo List

### ISSUE THREAD

**Issue by jdlawton** [jdlawton/fo4-char-gen#17]
- [ ] Code de-leveling to back up. (Not needed before Demo)
- [ ] Delete character from dashboard. (Not needed before Demo)
- [ ] Derived stats displayed on character view / edit page. (Not needed before Demo)
- [ ] Style Front-end (Should be partially done before Demo)
- [ ] Write copy for front-end (Should be partially done before Demo)
**- [ ] Demo Presentation (NEEDS to be done by Demo)
- [ ] Finish seeds file (Should be done by Demo)
- [ ] PDF Creation (Able to create file by Demo, doesn't need to be perfectly formatted)
- [ ] Verify laptop is ready and can develop this project (Needs to be ready by Tuesday Night)**
